### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics'

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/roboflow-python#103]
As discussed @FrancescoSaverioZuppichini implemented an automatic check to validate if the currently installed version of `ultralytics` is correct. However, we have not handled the case when `ultralytics` is not installed. An error then appears:

```
    module = import_module(dependency)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ultralytics'
```

I think we shouldn't throw exception when `ultralytics` is not installed.

**Comment by FrancescoSaverioZuppichini** [comment]
That is intended behaviour, is the module is not there is crashing. Do you think it would be better if I `catch` it and print a nicer message?

**Comment by SkalskiP** [comment]
Yup. Crushing is the least user-friendly behavior. What if they want to download the dataset? I'd catch that and print some descriptive info/working.

**Comment by FrancescoSaverioZuppichini** [comment]
No, crushing when necessary is the correct behaviour. In this case, it isn't so I'll add a message somewhere
