### ISSUE TITLE
bug when ultralytics is installed in env and dataset is being downloaded as coco

### ISSUE THREAD

**Issue by fcakyon** [roboflow/roboflow-python#118]
@SkalskiP hello, [this line](https://github.com/roboflow/roboflow-python/pull/113/files/a3c42c32ce18254b528cfb1c5089acb624018cda#diff-3c27c7c87d002c756c070d889087af1c6b3766419d62c03d832267ed004beaebR585) raises error when downloading a dataset in coco format and ultralytics>=8.0.30 is installed in the environment.

I believe this is a bug.

reproduction:

```python
rf = roboflow.Roboflow(api_key=api_key)
project = rf.workspace(workspace).project(project)
dataset.download("coco", location=location)
```

raises this error:

```bash
Exception has occurred: FileNotFoundError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
[Errno 2] No such file or directory: 'data/data.yaml'
```

**Comment by SkalskiP** [comment]
You are right. That behavior is unintended. I'll prepare a quick fix.
