### ISSUE TITLE
missing 1 required positional argument: 'image_dims'

### ISSUE THREAD

**Issue by aggiehorns** [roboflow/roboflow-python#124]
Hello.  Working on a project that current plugs into roboflow and getting the following exception.

  ```
File "/home/intellisite/.local/lib/python3.8/site-packages/roboflow/models/classification.py", line 68, in predict
    return PredictionGroup.create_prediction_group(
TypeError: create_prediction_group() missing 1 required positional argument: 'image_dims'
Exception : create_prediction_group() missing 1 required positional argument: 'image_dims'
```

This is with latest version, 0.2.32, on a jetson.  I am not however sure about the version of the inference server running in a docker container.  Perhaps they are out of sync in some way.  Does anybody recognize this exception, how should I proceed?  Thanks!

**Comment by aggiehorns** [comment]
Some additional info.  The code I am trying to run supposedly works on another machine, which has the 0.2.25 py module installed.  Have there been breaking changes to the API between 0.2.25 and 0.2.32 that would explain this behavior?

**Comment by iurisilvio** [comment]
I think it was fixed long time ago, probably by this commit: https://github.com/roboflow/roboflow-python/commit/1eded918ac89cf0828830a8c5a568bf598eb3cbe

Thanks for the report!
