### ISSUE TITLE
PredictionGroup.json() doesn't return valid JSON

### ISSUE THREAD

**Issue by saschwarz** [roboflow/roboflow-python#143]
After calling `results = model.predict("myfile.jpg").json()` the payload returned does not validate according to sites like: https://jsonlint.com/. 

Keys/values are single quoted instead of double quoted:

```
>>> results.json()
{'predictions': [{'x': 152.0, 'y': 123.0, 'width': 32.0, 'height': 26.0, 'confidence': 0.9857234954833984, 'class': 'Winged OneJump', 'points': [{'x': 139.20000000000002, 'y': 135.38482469517615}, {'x': 135.68153170952408, 'y': 135.203125}, {'x': 136.0, 'y': 130.249381671132}, {'x': 142.4, 'y': 127.0368981888704}, {'x': 144.8, 'y': 124.01929928394047}, {'x': 158.4, 'y': 114.30675322517745}, {'x': 162.4, 'y': 109.65927292747966}, {'x': 167.38880649064447, 'y': 109.753125}, {'x': 167.22471267469234, 'y': 113.7296875}, {'x': 164.8, 'y': 116.23254140522035}, {'x': 160.8, 'y': 117.12242613503112}, {'x': 157.60000000000002, 'y': 120.14261215838174},...
```

**Comment by capjamesg** [comment]
Hello @saschwarz! I believe this pertains to how the Python REPL handles dictionary serialization:

```python
>>> example = {"example": "roboflow"}
>>> print(example)
{'example': 'roboflow'}
>>> import json
>>> print(json.dumps(example))
{"example": "roboflow"}
```

Here, the dictionary printed out returns a string with the single quotes (not valid JSON). When you serialize the object with the `json.dumps()` method, it is loaded into valid JSON.

If you run `print(results.json())` you will get the same valid JSON output. We do this in the `__str__` method which runs whenever you call `print()` on the `results` object.
