### ISSUE TITLE
Verbosity causing IO issues in Kaggle

### ISSUE THREAD

**Issue by stellasphere** [roboflow/roboflow-python#164]
Related to this issue raised on the forum: https://discuss.roboflow.com/t/kaggle-io-error-when-downloading-dataset/2936/8

The constant updates from the download/extracting progress are causing issues by triggering suspected IO rate limits in Kaggle's "Save and Run All (Commit)" option.

**Comment by capjamesg** [comment]
This was addressed in https://github.com/roboflow/roboflow-python/pull/179.
