### ISSUE TITLE
Generated masks lack labeled polygons as well as don't match Roboflow interface (Critical, Bug)

### ISSUE THREAD

**Issue by alexgureev** [roboflow/roboflow-python#165]
Hi,

For semantic segmentation dataset we noticed that generated masks don't have all information that the team annotated in the Roboflow app. For example:

Image 1
![bug_1](https://github.com/roboflow/roboflow-python/assets/1176312/b51c8672-330b-4715-9410-b27bda43426a)
On the left original image, and on the right generated mask. Notice that the doors on the right and right-top are not present in the mask. On the images below you may see how the layers and classes are structured at the Roboflow's interface:
<img width="992" alt="roboflow_layers_1" src="https://github.com/roboflow/roboflow-python/assets/1176312/607a7ded-d5bb-4524-b345-b8fa229a1694">
<img width="948" alt="roboflow_classes_1" src="https://github.com/roboflow/roboflow-python/assets/1176312/99447fa2-1a10-46fd-9fe3-f7d255f2062e">

In our opinion, the cause of the discrepancy is the way how masks file generated and the layers information is unpacked. 

We have many example in our dataset that expose the same issue. It significantly affects our model training quality. Also, to overcome the issue we spend much more time on labeling that we wanted.

**Comment by tonylampada** [comment]
Fixed! Thanks for reporting :-)
