### ISSUE TITLE
 xyxy must be 2d np.ndarray with (n, 4) shape (BUG)

### ISSUE THREAD

**Issue by xmsi** [roboflow/roboflow-python#172]
roboflow==1.1.4
![Screenshot from 2023-08-25 09-46-13](https://github.com/roboflow/roboflow-python/assets/59314275/e3a2d52c-860b-4180-a4ad-a80d2db0913d)
even xml is proper 
![Screenshot from 2023-08-25 09-44-22](https://github.com/roboflow/roboflow-python/assets/59314275/3eeaf31e-5683-4f5c-99d9-db1088ea58ae)

**Comment by onuralpszr** [comment]
@xmsi this is an supervision we fixed a week ago (hopefully) and pushed a code for that in here https://github.com/roboflow/supervision/issues/347 could you try git version  If you problem solved that is awesome if not let's open a issue in https://github.com/roboflow/supervision and possibly with colab/code with dataset you used (if public and okey to share)  so we can investigate better as well :)

**Comment by capjamesg** [comment]
I am going to close this Issue since it is unrelated to `roboflow-python`. Please continue discussion in the `supervision` repository as noted by @onuralpszr above.
