### ISSUE TITLE
Batches generated from python package are named `None`

### ISSUE THREAD

**Issue by iurisilvio** [roboflow/roboflow-python#263]
I published something using `roboflow-python` and the batch name was `None`.

![image](https://github.com/roboflow/roboflow/assets/105852/8a5de854-5618-4962-92fa-93da839bee2c)

```python
import roboflow
rf = roboflow.Roboflow()
project = rf.workspace().project("PROJECT_ID")
project.upload(image_path="YOUR_IMAGE.jpg")
```

**Comment by joaomarcoscrs** [comment]
Not sure this is the best way. The upload_image at roboflowpy.py takes an dict as an argument, the best thing would be to refactor it to be more explicit of what's inside of it

https://github.com/roboflow/roboflow-python/pull/278
