### ISSUE TITLE
Suggestion to add more drawing tools

### ISSUE THREAD

**Issue by IvanHahan** [roboflow/roboflow-python#336]
Don't know where to put this suggestion, so adding it here as an issue

I need to extract a directed relationships between detected entities. For this purpose I need the tool to create such annotations. In roboflow I can create only rectangular and polygonal shapes. I'd like to  add arrows or smth to establish directed connection between rectangular annotations

**Comment by yeldarby** [comment]
Hi, [supervision](https://roboflow.com/supervision) is our open source package that handles this kind of thing. We have a bunch of [annotators](https://supervision.roboflow.com/annotators/) but no arrows yet; could definitely extend it with your own annotators to represent your object's relationships.
