### ISSUE TITLE
Prediction group colors do not match project colors

### ISSUE THREAD

**Issue by Jacobsolawetz** [roboflow/roboflow-python#47]
The project colors are available from the REST API, available on the `project` object

![image](https://user-images.githubusercontent.com/8428198/189983336-3434d58a-11d8-499c-85fb-9090a84dcdc5.png)

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @Jacobsolawetz, could you please provide more context to this issue? Let me know if we have an issue template, otherwise it may be a good idea to create one

**Comment by FrancescoSaverioZuppichini** [comment]
@Jacobsolawetz ping
